name: Report a bug
description: What went wrong?
labels: [bug]

body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this request!
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the issue
      placeholder: Tell us what happened
    validations:
      required: true
